# Site settings
title: DanPosts | Where dan posts
description: "DanPosts | Where dan posts"
url: "https://danposts.com/"
author:
  name: "Dan Hodges"
  email: "dhdgs690@gmail.com"
  url: "http://www.danhodges.github.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/
tag_page_layout: tag_page
tag_page_dir: tag

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-crosspost-to-medium

# Custom variables
version: "1.0.0"

# Options
custom_header: true
custom_nav_footer: false
reverse: false
